apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  selector:
    app: kafka
  type: NodePort
  ports:
  - nodePort: 30004
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-clusterip
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-clusterip.zookeeper.svc.cluster.local:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.0.101:30004
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: kafka-storage
          mountPath: /bitnami/kafka
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: kafka
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: kafka
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  path: "/mnt/storage/kafka"